#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TramYTe.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TramYTe")]
	public partial class dbTYTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDinhDuong(DinhDuong instance);
    partial void UpdateDinhDuong(DinhDuong instance);
    partial void DeleteDinhDuong(DinhDuong instance);
    partial void InsertVaccine(Vaccine instance);
    partial void UpdateVaccine(Vaccine instance);
    partial void DeleteVaccine(Vaccine instance);
    partial void InsertHoGiaDinh(HoGiaDinh instance);
    partial void UpdateHoGiaDinh(HoGiaDinh instance);
    partial void DeleteHoGiaDinh(HoGiaDinh instance);
    partial void InsertKhuPho(KhuPho instance);
    partial void UpdateKhuPho(KhuPho instance);
    partial void DeleteKhuPho(KhuPho instance);
    partial void InsertLichTiemVaccine(LichTiemVaccine instance);
    partial void UpdateLichTiemVaccine(LichTiemVaccine instance);
    partial void DeleteLichTiemVaccine(LichTiemVaccine instance);
    partial void InsertPhongKham(PhongKham instance);
    partial void UpdatePhongKham(PhongKham instance);
    partial void DeletePhongKham(PhongKham instance);
    partial void InsertTaiKhoanDangNhap(TaiKhoanDangNhap instance);
    partial void UpdateTaiKhoanDangNhap(TaiKhoanDangNhap instance);
    partial void DeleteTaiKhoanDangNhap(TaiKhoanDangNhap instance);
    partial void InsertTiemChung(TiemChung instance);
    partial void UpdateTiemChung(TiemChung instance);
    partial void DeleteTiemChung(TiemChung instance);
    partial void InsertThaiKy(ThaiKy instance);
    partial void UpdateThaiKy(ThaiKy instance);
    partial void DeleteThaiKy(ThaiKy instance);
    partial void InsertThanhVien(ThanhVien instance);
    partial void UpdateThanhVien(ThanhVien instance);
    partial void DeleteThanhVien(ThanhVien instance);
    partial void InsertThongBao(ThongBao instance);
    partial void UpdateThongBao(ThongBao instance);
    partial void DeleteThongBao(ThongBao instance);
    #endregion
		
		public dbTYTDataContext() : 
				base(global::TramYTe.Properties.Settings.Default.TramYTeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbTYTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTYTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTYTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTYTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DinhDuong> DinhDuongs
		{
			get
			{
				return this.GetTable<DinhDuong>();
			}
		}
		
		public System.Data.Linq.Table<Vaccine> Vaccines
		{
			get
			{
				return this.GetTable<Vaccine>();
			}
		}
		
		public System.Data.Linq.Table<HoGiaDinh> HoGiaDinhs
		{
			get
			{
				return this.GetTable<HoGiaDinh>();
			}
		}
		
		public System.Data.Linq.Table<KhuPho> KhuPhos
		{
			get
			{
				return this.GetTable<KhuPho>();
			}
		}
		
		public System.Data.Linq.Table<LichTiemVaccine> LichTiemVaccines
		{
			get
			{
				return this.GetTable<LichTiemVaccine>();
			}
		}
		
		public System.Data.Linq.Table<PhongKham> PhongKhams
		{
			get
			{
				return this.GetTable<PhongKham>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanDangNhap> TaiKhoanDangNhaps
		{
			get
			{
				return this.GetTable<TaiKhoanDangNhap>();
			}
		}
		
		public System.Data.Linq.Table<TiemChung> TiemChungs
		{
			get
			{
				return this.GetTable<TiemChung>();
			}
		}
		
		public System.Data.Linq.Table<ThaiKy> ThaiKies
		{
			get
			{
				return this.GetTable<ThaiKy>();
			}
		}
		
		public System.Data.Linq.Table<ThanhVien> ThanhViens
		{
			get
			{
				return this.GetTable<ThanhVien>();
			}
		}
		
		public System.Data.Linq.Table<ThongBao> ThongBaos
		{
			get
			{
				return this.GetTable<ThongBao>();
			}
		}
		
		public System.Data.Linq.Table<TreBeoPhi> TreBeoPhis
		{
			get
			{
				return this.GetTable<TreBeoPhi>();
			}
		}
		
		public System.Data.Linq.Table<TreSuyDinhDuong> TreSuyDinhDuongs
		{
			get
			{
				return this.GetTable<TreSuyDinhDuong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DinhDuong")]
	public partial class DinhDuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuDinhDuong;
		
		private System.Nullable<double> _ChieuCao;
		
		private System.Nullable<double> _CanNang;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private string _MaThanhVien;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuDinhDuongChanging(string value);
    partial void OnMaPhieuDinhDuongChanged();
    partial void OnChieuCaoChanging(System.Nullable<double> value);
    partial void OnChieuCaoChanged();
    partial void OnCanNangChanging(System.Nullable<double> value);
    partial void OnCanNangChanged();
    partial void OnNgayKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhamChanged();
    partial void OnMaThanhVienChanging(string value);
    partial void OnMaThanhVienChanged();
    #endregion
		
		public DinhDuong()
		{
			this._ThanhVien = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDinhDuong", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuDinhDuong
		{
			get
			{
				return this._MaPhieuDinhDuong;
			}
			set
			{
				if ((this._MaPhieuDinhDuong != value))
				{
					this.OnMaPhieuDinhDuongChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDinhDuong = value;
					this.SendPropertyChanged("MaPhieuDinhDuong");
					this.OnMaPhieuDinhDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuCao", DbType="Float")]
		public System.Nullable<double> ChieuCao
		{
			get
			{
				return this._ChieuCao;
			}
			set
			{
				if ((this._ChieuCao != value))
				{
					this.OnChieuCaoChanging(value);
					this.SendPropertyChanging();
					this._ChieuCao = value;
					this.SendPropertyChanged("ChieuCao");
					this.OnChieuCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="VarChar(50)")]
		public string MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_DinhDuong", Storage="_ThanhVien", ThisKey="MaThanhVien", OtherKey="MaThanhVien", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.DinhDuongs.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.DinhDuongs.Add(this);
						this._MaThanhVien = value.MaThanhVien;
					}
					else
					{
						this._MaThanhVien = default(string);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vaccine")]
	public partial class Vaccine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVaccine;
		
		private string _TenVaccine;
		
		private string _MaLo;
		
		private System.Nullable<int> _SoLuong;
		
		private string _NhaSanXuat;
		
		private System.Nullable<int> _SoLuongDeXuat;
		
		private System.Nullable<System.DateTime> _NgaySanXuat;
		
		private System.Nullable<int> _HanSuDung;
		
		private System.Nullable<int> _ChuKyTiem;
		
		private EntitySet<TiemChung> _TiemChungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVaccineChanging(string value);
    partial void OnMaVaccineChanged();
    partial void OnTenVaccineChanging(string value);
    partial void OnTenVaccineChanged();
    partial void OnMaLoChanging(string value);
    partial void OnMaLoChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNhaSanXuatChanging(string value);
    partial void OnNhaSanXuatChanged();
    partial void OnSoLuongDeXuatChanging(System.Nullable<int> value);
    partial void OnSoLuongDeXuatChanged();
    partial void OnNgaySanXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySanXuatChanged();
    partial void OnHanSuDungChanging(System.Nullable<int> value);
    partial void OnHanSuDungChanged();
    partial void OnChuKyTiemChanging(System.Nullable<int> value);
    partial void OnChuKyTiemChanged();
    #endregion
		
		public Vaccine()
		{
			this._TiemChungs = new EntitySet<TiemChung>(new Action<TiemChung>(this.attach_TiemChungs), new Action<TiemChung>(this.detach_TiemChungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVaccine", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVaccine
		{
			get
			{
				return this._MaVaccine;
			}
			set
			{
				if ((this._MaVaccine != value))
				{
					this.OnMaVaccineChanging(value);
					this.SendPropertyChanging();
					this._MaVaccine = value;
					this.SendPropertyChanged("MaVaccine");
					this.OnMaVaccineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVaccine", DbType="NVarChar(200)")]
		public string TenVaccine
		{
			get
			{
				return this._TenVaccine;
			}
			set
			{
				if ((this._TenVaccine != value))
				{
					this.OnTenVaccineChanging(value);
					this.SendPropertyChanging();
					this._TenVaccine = value;
					this.SendPropertyChanged("TenVaccine");
					this.OnTenVaccineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLo", DbType="VarChar(50)")]
		public string MaLo
		{
			get
			{
				return this._MaLo;
			}
			set
			{
				if ((this._MaLo != value))
				{
					this.OnMaLoChanging(value);
					this.SendPropertyChanging();
					this._MaLo = value;
					this.SendPropertyChanged("MaLo");
					this.OnMaLoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaSanXuat", DbType="NVarChar(MAX)")]
		public string NhaSanXuat
		{
			get
			{
				return this._NhaSanXuat;
			}
			set
			{
				if ((this._NhaSanXuat != value))
				{
					this.OnNhaSanXuatChanging(value);
					this.SendPropertyChanging();
					this._NhaSanXuat = value;
					this.SendPropertyChanged("NhaSanXuat");
					this.OnNhaSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDeXuat", DbType="Int")]
		public System.Nullable<int> SoLuongDeXuat
		{
			get
			{
				return this._SoLuongDeXuat;
			}
			set
			{
				if ((this._SoLuongDeXuat != value))
				{
					this.OnSoLuongDeXuatChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDeXuat = value;
					this.SendPropertyChanged("SoLuongDeXuat");
					this.OnSoLuongDeXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySanXuat", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySanXuat
		{
			get
			{
				return this._NgaySanXuat;
			}
			set
			{
				if ((this._NgaySanXuat != value))
				{
					this.OnNgaySanXuatChanging(value);
					this.SendPropertyChanging();
					this._NgaySanXuat = value;
					this.SendPropertyChanged("NgaySanXuat");
					this.OnNgaySanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanSuDung", DbType="Int")]
		public System.Nullable<int> HanSuDung
		{
			get
			{
				return this._HanSuDung;
			}
			set
			{
				if ((this._HanSuDung != value))
				{
					this.OnHanSuDungChanging(value);
					this.SendPropertyChanging();
					this._HanSuDung = value;
					this.SendPropertyChanged("HanSuDung");
					this.OnHanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuKyTiem", DbType="Int")]
		public System.Nullable<int> ChuKyTiem
		{
			get
			{
				return this._ChuKyTiem;
			}
			set
			{
				if ((this._ChuKyTiem != value))
				{
					this.OnChuKyTiemChanging(value);
					this.SendPropertyChanging();
					this._ChuKyTiem = value;
					this.SendPropertyChanged("ChuKyTiem");
					this.OnChuKyTiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vaccine_TiemChung", Storage="_TiemChungs", ThisKey="MaVaccine", OtherKey="MaVaccine")]
		public EntitySet<TiemChung> TiemChungs
		{
			get
			{
				return this._TiemChungs;
			}
			set
			{
				this._TiemChungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TiemChungs(TiemChung entity)
		{
			this.SendPropertyChanging();
			entity.Vaccine = this;
		}
		
		private void detach_TiemChungs(TiemChung entity)
		{
			this.SendPropertyChanging();
			entity.Vaccine = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoGiaDinh")]
	public partial class HoGiaDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHo;
		
		private string _DiaChi;
		
		private string _Email;
		
		private string _MaKhuPho;
		
		private EntitySet<TaiKhoanDangNhap> _TaiKhoanDangNhaps;
		
		private EntitySet<ThanhVien> _ThanhViens;
		
		private EntitySet<ThongBao> _ThongBaos;
		
		private EntityRef<KhuPho> _KhuPho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoChanging(string value);
    partial void OnMaHoChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMaKhuPhoChanging(string value);
    partial void OnMaKhuPhoChanged();
    #endregion
		
		public HoGiaDinh()
		{
			this._TaiKhoanDangNhaps = new EntitySet<TaiKhoanDangNhap>(new Action<TaiKhoanDangNhap>(this.attach_TaiKhoanDangNhaps), new Action<TaiKhoanDangNhap>(this.detach_TaiKhoanDangNhaps));
			this._ThanhViens = new EntitySet<ThanhVien>(new Action<ThanhVien>(this.attach_ThanhViens), new Action<ThanhVien>(this.detach_ThanhViens));
			this._ThongBaos = new EntitySet<ThongBao>(new Action<ThongBao>(this.attach_ThongBaos), new Action<ThongBao>(this.detach_ThongBaos));
			this._KhuPho = default(EntityRef<KhuPho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHo
		{
			get
			{
				return this._MaHo;
			}
			set
			{
				if ((this._MaHo != value))
				{
					this.OnMaHoChanging(value);
					this.SendPropertyChanging();
					this._MaHo = value;
					this.SendPropertyChanged("MaHo");
					this.OnMaHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuPho", DbType="VarChar(50)")]
		public string MaKhuPho
		{
			get
			{
				return this._MaKhuPho;
			}
			set
			{
				if ((this._MaKhuPho != value))
				{
					if (this._KhuPho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhuPhoChanging(value);
					this.SendPropertyChanging();
					this._MaKhuPho = value;
					this.SendPropertyChanged("MaKhuPho");
					this.OnMaKhuPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoGiaDinh_TaiKhoanDangNhap", Storage="_TaiKhoanDangNhaps", ThisKey="MaHo", OtherKey="MaHo")]
		public EntitySet<TaiKhoanDangNhap> TaiKhoanDangNhaps
		{
			get
			{
				return this._TaiKhoanDangNhaps;
			}
			set
			{
				this._TaiKhoanDangNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoGiaDinh_ThanhVien", Storage="_ThanhViens", ThisKey="MaHo", OtherKey="MaHo")]
		public EntitySet<ThanhVien> ThanhViens
		{
			get
			{
				return this._ThanhViens;
			}
			set
			{
				this._ThanhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoGiaDinh_ThongBao", Storage="_ThongBaos", ThisKey="MaHo", OtherKey="MaHo")]
		public EntitySet<ThongBao> ThongBaos
		{
			get
			{
				return this._ThongBaos;
			}
			set
			{
				this._ThongBaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuPho_HoGiaDinh", Storage="_KhuPho", ThisKey="MaKhuPho", OtherKey="MaKhuPho", IsForeignKey=true)]
		public KhuPho KhuPho
		{
			get
			{
				return this._KhuPho.Entity;
			}
			set
			{
				KhuPho previousValue = this._KhuPho.Entity;
				if (((previousValue != value) 
							|| (this._KhuPho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuPho.Entity = null;
						previousValue.HoGiaDinhs.Remove(this);
					}
					this._KhuPho.Entity = value;
					if ((value != null))
					{
						value.HoGiaDinhs.Add(this);
						this._MaKhuPho = value.MaKhuPho;
					}
					else
					{
						this._MaKhuPho = default(string);
					}
					this.SendPropertyChanged("KhuPho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoanDangNhaps(TaiKhoanDangNhap entity)
		{
			this.SendPropertyChanging();
			entity.HoGiaDinh = this;
		}
		
		private void detach_TaiKhoanDangNhaps(TaiKhoanDangNhap entity)
		{
			this.SendPropertyChanging();
			entity.HoGiaDinh = null;
		}
		
		private void attach_ThanhViens(ThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.HoGiaDinh = this;
		}
		
		private void detach_ThanhViens(ThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.HoGiaDinh = null;
		}
		
		private void attach_ThongBaos(ThongBao entity)
		{
			this.SendPropertyChanging();
			entity.HoGiaDinh = this;
		}
		
		private void detach_ThongBaos(ThongBao entity)
		{
			this.SendPropertyChanging();
			entity.HoGiaDinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuPho")]
	public partial class KhuPho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhuPho;
		
		private string _TenKhuPho;
		
		private EntitySet<HoGiaDinh> _HoGiaDinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhuPhoChanging(string value);
    partial void OnMaKhuPhoChanged();
    partial void OnTenKhuPhoChanging(string value);
    partial void OnTenKhuPhoChanged();
    #endregion
		
		public KhuPho()
		{
			this._HoGiaDinhs = new EntitySet<HoGiaDinh>(new Action<HoGiaDinh>(this.attach_HoGiaDinhs), new Action<HoGiaDinh>(this.detach_HoGiaDinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuPho", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhuPho
		{
			get
			{
				return this._MaKhuPho;
			}
			set
			{
				if ((this._MaKhuPho != value))
				{
					this.OnMaKhuPhoChanging(value);
					this.SendPropertyChanging();
					this._MaKhuPho = value;
					this.SendPropertyChanged("MaKhuPho");
					this.OnMaKhuPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhuPho", DbType="NVarChar(100)")]
		public string TenKhuPho
		{
			get
			{
				return this._TenKhuPho;
			}
			set
			{
				if ((this._TenKhuPho != value))
				{
					this.OnTenKhuPhoChanging(value);
					this.SendPropertyChanging();
					this._TenKhuPho = value;
					this.SendPropertyChanged("TenKhuPho");
					this.OnTenKhuPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuPho_HoGiaDinh", Storage="_HoGiaDinhs", ThisKey="MaKhuPho", OtherKey="MaKhuPho")]
		public EntitySet<HoGiaDinh> HoGiaDinhs
		{
			get
			{
				return this._HoGiaDinhs;
			}
			set
			{
				this._HoGiaDinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoGiaDinhs(HoGiaDinh entity)
		{
			this.SendPropertyChanging();
			entity.KhuPho = this;
		}
		
		private void detach_HoGiaDinhs(HoGiaDinh entity)
		{
			this.SendPropertyChanging();
			entity.KhuPho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichTiemVaccine")]
	public partial class LichTiemVaccine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLichTiem;
		
		private System.Nullable<System.DateTime> _NgayTiem;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichTiemChanging(int value);
    partial void OnMaLichTiemChanged();
    partial void OnNgayTiemChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTiemChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public LichTiemVaccine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichTiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLichTiem
		{
			get
			{
				return this._MaLichTiem;
			}
			set
			{
				if ((this._MaLichTiem != value))
				{
					this.OnMaLichTiemChanging(value);
					this.SendPropertyChanging();
					this._MaLichTiem = value;
					this.SendPropertyChanged("MaLichTiem");
					this.OnMaLichTiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTiem", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTiem
		{
			get
			{
				return this._NgayTiem;
			}
			set
			{
				if ((this._NgayTiem != value))
				{
					this.OnNgayTiemChanging(value);
					this.SendPropertyChanging();
					this._NgayTiem = value;
					this.SendPropertyChanged("NgayTiem");
					this.OnNgayTiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongKham")]
	public partial class PhongKham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhongKham;
		
		private string _TenPhongKham;
		
		private string _NoiDung;
		
		private string _MaThanhVien;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongKhamChanging(string value);
    partial void OnMaPhongKhamChanged();
    partial void OnTenPhongKhamChanging(string value);
    partial void OnTenPhongKhamChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnMaThanhVienChanging(string value);
    partial void OnMaThanhVienChanged();
    #endregion
		
		public PhongKham()
		{
			this._ThanhVien = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongKham", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhongKham
		{
			get
			{
				return this._MaPhongKham;
			}
			set
			{
				if ((this._MaPhongKham != value))
				{
					this.OnMaPhongKhamChanging(value);
					this.SendPropertyChanging();
					this._MaPhongKham = value;
					this.SendPropertyChanged("MaPhongKham");
					this.OnMaPhongKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongKham", DbType="NVarChar(200)")]
		public string TenPhongKham
		{
			get
			{
				return this._TenPhongKham;
			}
			set
			{
				if ((this._TenPhongKham != value))
				{
					this.OnTenPhongKhamChanging(value);
					this.SendPropertyChanging();
					this._TenPhongKham = value;
					this.SendPropertyChanged("TenPhongKham");
					this.OnTenPhongKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="VarChar(50)")]
		public string MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_PhongKham", Storage="_ThanhVien", ThisKey="MaThanhVien", OtherKey="MaThanhVien", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.PhongKhams.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.PhongKhams.Add(this);
						this._MaThanhVien = value.MaThanhVien;
					}
					else
					{
						this._MaThanhVien = default(string);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanDangNhap")]
	public partial class TaiKhoanDangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _MaHo;
		
		private string _Quyen;
		
		private EntityRef<HoGiaDinh> _HoGiaDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaHoChanging(string value);
    partial void OnMaHoChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public TaiKhoanDangNhap()
		{
			this._HoGiaDinh = default(EntityRef<HoGiaDinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHo", DbType="VarChar(50)")]
		public string MaHo
		{
			get
			{
				return this._MaHo;
			}
			set
			{
				if ((this._MaHo != value))
				{
					if (this._HoGiaDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoChanging(value);
					this.SendPropertyChanging();
					this._MaHo = value;
					this.SendPropertyChanged("MaHo");
					this.OnMaHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="VarChar(5)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoGiaDinh_TaiKhoanDangNhap", Storage="_HoGiaDinh", ThisKey="MaHo", OtherKey="MaHo", IsForeignKey=true)]
		public HoGiaDinh HoGiaDinh
		{
			get
			{
				return this._HoGiaDinh.Entity;
			}
			set
			{
				HoGiaDinh previousValue = this._HoGiaDinh.Entity;
				if (((previousValue != value) 
							|| (this._HoGiaDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoGiaDinh.Entity = null;
						previousValue.TaiKhoanDangNhaps.Remove(this);
					}
					this._HoGiaDinh.Entity = value;
					if ((value != null))
					{
						value.TaiKhoanDangNhaps.Add(this);
						this._MaHo = value.MaHo;
					}
					else
					{
						this._MaHo = default(string);
					}
					this.SendPropertyChanged("HoGiaDinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiemChung")]
	public partial class TiemChung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuTiemChung;
		
		private string _MaVaccine;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<System.DateTime> _NgayTiem;
		
		private string _TrieuChungSauTiem;
		
		private string _MaThanhVien;
		
		private bool _TrangThai;
		
		private EntityRef<Vaccine> _Vaccine;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuTiemChungChanging(string value);
    partial void OnMaPhieuTiemChungChanged();
    partial void OnMaVaccineChanging(string value);
    partial void OnMaVaccineChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNgayTiemChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTiemChanged();
    partial void OnTrieuChungSauTiemChanging(string value);
    partial void OnTrieuChungSauTiemChanged();
    partial void OnMaThanhVienChanging(string value);
    partial void OnMaThanhVienChanged();
    partial void OnTrangThaiChanging(bool value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public TiemChung()
		{
			this._Vaccine = default(EntityRef<Vaccine>);
			this._ThanhVien = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuTiemChung", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuTiemChung
		{
			get
			{
				return this._MaPhieuTiemChung;
			}
			set
			{
				if ((this._MaPhieuTiemChung != value))
				{
					this.OnMaPhieuTiemChungChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuTiemChung = value;
					this.SendPropertyChanged("MaPhieuTiemChung");
					this.OnMaPhieuTiemChungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVaccine", DbType="VarChar(50)")]
		public string MaVaccine
		{
			get
			{
				return this._MaVaccine;
			}
			set
			{
				if ((this._MaVaccine != value))
				{
					if (this._Vaccine.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVaccineChanging(value);
					this.SendPropertyChanging();
					this._MaVaccine = value;
					this.SendPropertyChanged("MaVaccine");
					this.OnMaVaccineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTiem", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTiem
		{
			get
			{
				return this._NgayTiem;
			}
			set
			{
				if ((this._NgayTiem != value))
				{
					this.OnNgayTiemChanging(value);
					this.SendPropertyChanging();
					this._NgayTiem = value;
					this.SendPropertyChanged("NgayTiem");
					this.OnNgayTiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrieuChungSauTiem", DbType="NVarChar(MAX)")]
		public string TrieuChungSauTiem
		{
			get
			{
				return this._TrieuChungSauTiem;
			}
			set
			{
				if ((this._TrieuChungSauTiem != value))
				{
					this.OnTrieuChungSauTiemChanging(value);
					this.SendPropertyChanging();
					this._TrieuChungSauTiem = value;
					this.SendPropertyChanged("TrieuChungSauTiem");
					this.OnTrieuChungSauTiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="VarChar(50)")]
		public string MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit NOT NULL")]
		public bool TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vaccine_TiemChung", Storage="_Vaccine", ThisKey="MaVaccine", OtherKey="MaVaccine", IsForeignKey=true)]
		public Vaccine Vaccine
		{
			get
			{
				return this._Vaccine.Entity;
			}
			set
			{
				Vaccine previousValue = this._Vaccine.Entity;
				if (((previousValue != value) 
							|| (this._Vaccine.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vaccine.Entity = null;
						previousValue.TiemChungs.Remove(this);
					}
					this._Vaccine.Entity = value;
					if ((value != null))
					{
						value.TiemChungs.Add(this);
						this._MaVaccine = value.MaVaccine;
					}
					else
					{
						this._MaVaccine = default(string);
					}
					this.SendPropertyChanged("Vaccine");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_TiemChung", Storage="_ThanhVien", ThisKey="MaThanhVien", OtherKey="MaThanhVien", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.TiemChungs.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.TiemChungs.Add(this);
						this._MaThanhVien = value.MaThanhVien;
					}
					else
					{
						this._MaThanhVien = default(string);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThaiKy")]
	public partial class ThaiKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuKhamThai;
		
		private System.Nullable<double> _CanNang;
		
		private System.Nullable<System.DateTime> _NgayMangThai;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private string _MaThanhVien;
		
		private System.Nullable<System.DateTime> _NgayTaiKham;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuKhamThaiChanging(string value);
    partial void OnMaPhieuKhamThaiChanged();
    partial void OnCanNangChanging(System.Nullable<double> value);
    partial void OnCanNangChanged();
    partial void OnNgayMangThaiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMangThaiChanged();
    partial void OnNgayKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhamChanged();
    partial void OnMaThanhVienChanging(string value);
    partial void OnMaThanhVienChanged();
    partial void OnNgayTaiKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaiKhamChanged();
    #endregion
		
		public ThaiKy()
		{
			this._ThanhVien = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuKhamThai", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuKhamThai
		{
			get
			{
				return this._MaPhieuKhamThai;
			}
			set
			{
				if ((this._MaPhieuKhamThai != value))
				{
					this.OnMaPhieuKhamThaiChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuKhamThai = value;
					this.SendPropertyChanged("MaPhieuKhamThai");
					this.OnMaPhieuKhamThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMangThai", DbType="Date")]
		public System.Nullable<System.DateTime> NgayMangThai
		{
			get
			{
				return this._NgayMangThai;
			}
			set
			{
				if ((this._NgayMangThai != value))
				{
					this.OnNgayMangThaiChanging(value);
					this.SendPropertyChanging();
					this._NgayMangThai = value;
					this.SendPropertyChanged("NgayMangThai");
					this.OnNgayMangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="VarChar(50)")]
		public string MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTaiKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTaiKham
		{
			get
			{
				return this._NgayTaiKham;
			}
			set
			{
				if ((this._NgayTaiKham != value))
				{
					this.OnNgayTaiKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayTaiKham = value;
					this.SendPropertyChanged("NgayTaiKham");
					this.OnNgayTaiKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_ThaiKy", Storage="_ThanhVien", ThisKey="MaThanhVien", OtherKey="MaThanhVien", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.ThaiKies.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.ThaiKies.Add(this);
						this._MaThanhVien = value.MaThanhVien;
					}
					else
					{
						this._MaThanhVien = default(string);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVien")]
	public partial class ThanhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThanhVien;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DienThoai;
		
		private string _CCCD;
		
		private string _MaHo;
		
		private string _LichSuBenhAn;
		
		private EntitySet<DinhDuong> _DinhDuongs;
		
		private EntitySet<PhongKham> _PhongKhams;
		
		private EntitySet<TiemChung> _TiemChungs;
		
		private EntitySet<ThaiKy> _ThaiKies;
		
		private EntityRef<HoGiaDinh> _HoGiaDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhVienChanging(string value);
    partial void OnMaThanhVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnMaHoChanging(string value);
    partial void OnMaHoChanged();
    partial void OnLichSuBenhAnChanging(string value);
    partial void OnLichSuBenhAnChanged();
    #endregion
		
		public ThanhVien()
		{
			this._DinhDuongs = new EntitySet<DinhDuong>(new Action<DinhDuong>(this.attach_DinhDuongs), new Action<DinhDuong>(this.detach_DinhDuongs));
			this._PhongKhams = new EntitySet<PhongKham>(new Action<PhongKham>(this.attach_PhongKhams), new Action<PhongKham>(this.detach_PhongKhams));
			this._TiemChungs = new EntitySet<TiemChung>(new Action<TiemChung>(this.attach_TiemChungs), new Action<TiemChung>(this.detach_TiemChungs));
			this._ThaiKies = new EntitySet<ThaiKy>(new Action<ThaiKy>(this.attach_ThaiKies), new Action<ThaiKy>(this.detach_ThaiKies));
			this._HoGiaDinh = default(EntityRef<HoGiaDinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(150)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHo", DbType="VarChar(50)")]
		public string MaHo
		{
			get
			{
				return this._MaHo;
			}
			set
			{
				if ((this._MaHo != value))
				{
					if (this._HoGiaDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoChanging(value);
					this.SendPropertyChanging();
					this._MaHo = value;
					this.SendPropertyChanged("MaHo");
					this.OnMaHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LichSuBenhAn", DbType="NVarChar(MAX)")]
		public string LichSuBenhAn
		{
			get
			{
				return this._LichSuBenhAn;
			}
			set
			{
				if ((this._LichSuBenhAn != value))
				{
					this.OnLichSuBenhAnChanging(value);
					this.SendPropertyChanging();
					this._LichSuBenhAn = value;
					this.SendPropertyChanged("LichSuBenhAn");
					this.OnLichSuBenhAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_DinhDuong", Storage="_DinhDuongs", ThisKey="MaThanhVien", OtherKey="MaThanhVien")]
		public EntitySet<DinhDuong> DinhDuongs
		{
			get
			{
				return this._DinhDuongs;
			}
			set
			{
				this._DinhDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_PhongKham", Storage="_PhongKhams", ThisKey="MaThanhVien", OtherKey="MaThanhVien")]
		public EntitySet<PhongKham> PhongKhams
		{
			get
			{
				return this._PhongKhams;
			}
			set
			{
				this._PhongKhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_TiemChung", Storage="_TiemChungs", ThisKey="MaThanhVien", OtherKey="MaThanhVien")]
		public EntitySet<TiemChung> TiemChungs
		{
			get
			{
				return this._TiemChungs;
			}
			set
			{
				this._TiemChungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_ThaiKy", Storage="_ThaiKies", ThisKey="MaThanhVien", OtherKey="MaThanhVien")]
		public EntitySet<ThaiKy> ThaiKies
		{
			get
			{
				return this._ThaiKies;
			}
			set
			{
				this._ThaiKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoGiaDinh_ThanhVien", Storage="_HoGiaDinh", ThisKey="MaHo", OtherKey="MaHo", IsForeignKey=true)]
		public HoGiaDinh HoGiaDinh
		{
			get
			{
				return this._HoGiaDinh.Entity;
			}
			set
			{
				HoGiaDinh previousValue = this._HoGiaDinh.Entity;
				if (((previousValue != value) 
							|| (this._HoGiaDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoGiaDinh.Entity = null;
						previousValue.ThanhViens.Remove(this);
					}
					this._HoGiaDinh.Entity = value;
					if ((value != null))
					{
						value.ThanhViens.Add(this);
						this._MaHo = value.MaHo;
					}
					else
					{
						this._MaHo = default(string);
					}
					this.SendPropertyChanged("HoGiaDinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DinhDuongs(DinhDuong entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_DinhDuongs(DinhDuong entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
		
		private void attach_PhongKhams(PhongKham entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_PhongKhams(PhongKham entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
		
		private void attach_TiemChungs(TiemChung entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_TiemChungs(TiemChung entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
		
		private void attach_ThaiKies(ThaiKy entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_ThaiKies(ThaiKy entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongBao")]
	public partial class ThongBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThongBao;
		
		private string _TenThongBao;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _ThoiGianGui;
		
		private string _MaHo;
		
		private EntityRef<HoGiaDinh> _HoGiaDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThongBaoChanging(int value);
    partial void OnMaThongBaoChanged();
    partial void OnTenThongBaoChanging(string value);
    partial void OnTenThongBaoChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnThoiGianGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianGuiChanged();
    partial void OnMaHoChanging(string value);
    partial void OnMaHoChanged();
    #endregion
		
		public ThongBao()
		{
			this._HoGiaDinh = default(EntityRef<HoGiaDinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThongBao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThongBao
		{
			get
			{
				return this._MaThongBao;
			}
			set
			{
				if ((this._MaThongBao != value))
				{
					this.OnMaThongBaoChanging(value);
					this.SendPropertyChanging();
					this._MaThongBao = value;
					this.SendPropertyChanged("MaThongBao");
					this.OnMaThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThongBao", DbType="NVarChar(300)")]
		public string TenThongBao
		{
			get
			{
				return this._TenThongBao;
			}
			set
			{
				if ((this._TenThongBao != value))
				{
					this.OnTenThongBaoChanging(value);
					this.SendPropertyChanging();
					this._TenThongBao = value;
					this.SendPropertyChanged("TenThongBao");
					this.OnTenThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianGui", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianGui
		{
			get
			{
				return this._ThoiGianGui;
			}
			set
			{
				if ((this._ThoiGianGui != value))
				{
					this.OnThoiGianGuiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianGui = value;
					this.SendPropertyChanged("ThoiGianGui");
					this.OnThoiGianGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHo", DbType="VarChar(50)")]
		public string MaHo
		{
			get
			{
				return this._MaHo;
			}
			set
			{
				if ((this._MaHo != value))
				{
					if (this._HoGiaDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoChanging(value);
					this.SendPropertyChanging();
					this._MaHo = value;
					this.SendPropertyChanged("MaHo");
					this.OnMaHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoGiaDinh_ThongBao", Storage="_HoGiaDinh", ThisKey="MaHo", OtherKey="MaHo", IsForeignKey=true)]
		public HoGiaDinh HoGiaDinh
		{
			get
			{
				return this._HoGiaDinh.Entity;
			}
			set
			{
				HoGiaDinh previousValue = this._HoGiaDinh.Entity;
				if (((previousValue != value) 
							|| (this._HoGiaDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoGiaDinh.Entity = null;
						previousValue.ThongBaos.Remove(this);
					}
					this._HoGiaDinh.Entity = value;
					if ((value != null))
					{
						value.ThongBaos.Add(this);
						this._MaHo = value.MaHo;
					}
					else
					{
						this._MaHo = default(string);
					}
					this.SendPropertyChanged("HoGiaDinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TreBeoPhi")]
	public partial class TreBeoPhi
	{
		
		private string _GioiTinh;
		
		private System.Nullable<int> _ThangTuoi;
		
		private System.Nullable<double> _CanNang;
		
		public TreBeoPhi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThangTuoi", DbType="Int")]
		public System.Nullable<int> ThangTuoi
		{
			get
			{
				return this._ThangTuoi;
			}
			set
			{
				if ((this._ThangTuoi != value))
				{
					this._ThangTuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this._CanNang = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TreSuyDinhDuong")]
	public partial class TreSuyDinhDuong
	{
		
		private string _GioiTinh;
		
		private System.Nullable<int> _ThangTuoi;
		
		private System.Nullable<double> _CanNang;
		
		public TreSuyDinhDuong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThangTuoi", DbType="Int")]
		public System.Nullable<int> ThangTuoi
		{
			get
			{
				return this._ThangTuoi;
			}
			set
			{
				if ((this._ThangTuoi != value))
				{
					this._ThangTuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this._CanNang = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
